baseurl: "https://atelier-reticulum.netlify.app/"
languageCode: "fr-FR"
title: "Atelier Reticulum"
theme: "xmin"
footnotereturnlinkcontents: "↩"
buildFuture: true

permalinks:
  articles: ":filename/"

menu:
  main:
    - name: Accueil
      url: ""
      weight: 1
    - name: Version en ligne
      url: "0-editorial/"
      weight: 2
    - name: Version imprimable
      url: "imprimer/"
      weight: 3
    - name: Crédits
      url: "credits/"
      weight: 4

params:
  description: "Prototype de revue développé dans le cadre de l'atelier Reticulum."
  footer: "CC-BY Master DIIS, Master DNHD, Florian Harmand & Arthur Perret 2020 • [Contact](mailto:florian.harman@gmail.com,arthur.perret@u-bordeaux-montaigne.fr)"

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingID: true
      autoHeadingIDType: github-ascii
